from pathlib import Path

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 660
SCREEN_TITLE = "Громик/Пичик"
GAME_DURATION=30

SCROLL_SPEED = 400
GROUND_Y = 90
AIR_Y = 450


INTENSITY_MIN = 20
INTENSITY_MAX = 90
SMOOTHING_ALPHA = 0.6
RESPONSE_FACTOR = 0.4
chastota=3

BLOCKSIZE = 1024
SILENCE_THRESHOLD_DB = 53.0
BLOCKS_TO_SILENT = 4



ARTIFACTS_IN_WAVE=4
ARTIFACT_INTERVAL=2
ARTIFACT_SCORE = 10

TEXTURE_ONE = str(Path("games/gromik/components/berries.png").absolute())